// services/brandingAssetsService.ts
import JSZip from 'jszip';
import { AppConfig } from '../types';

interface IconVariant {
  path: string;
  size: number;
}

const ICON_VARIANTS: IconVariant[] = [
  { path: 'res/mipmap-mdpi/ic_launcher.png', size: 48 },
  { path: 'res/mipmap-hdpi/ic_launcher.png', size: 72 },
  { path: 'res/mipmap-xhdpi/ic_launcher.png', size: 96 },
  { path: 'res/mipmap-xxhdpi/ic_launcher.png', size: 144 },
  { path: 'res/mipmap-xxxhdpi/ic_launcher.png', size: 192 },
  { path: 'store/play_store_512x512.png', size: 512 },
  { path: 'ios/AppIcon.appiconset/Icon-1024.png', size: 1024 },
  { path: 'web/favicon-32x32.png', size: 32 },
  { path: 'web/apple-touch-icon.png', size: 180 },
  { path: 'web/pwa-icon-192.png', size: 192 },
  { path: 'web/pwa-icon-512.png', size: 512 }
];

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = (err) => reject(err);
    img.src = src;
  });
}

function renderFallbackIconCanvas(config: AppConfig, size: number): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d');
  if (!ctx) return canvas;

  const bgColor = config.iconColor || '#2563eb';
  const textColor = config.iconTextColor || '#FFFFFF';
  const text = config.iconLabel || 'HS';

  const radius = size * 0.22;
  ctx.fillStyle = bgColor;
  ctx.beginPath();
  ctx.moveTo(radius, 0);
  ctx.lineTo(size - radius, 0);
  ctx.quadraticCurveTo(size, 0, size, radius);
  ctx.lineTo(size, size - radius);
  ctx.quadraticCurveTo(size, size, size - radius, size);
  ctx.lineTo(radius, size);
  ctx.quadraticCurveTo(0, size, 0, size - radius);
  ctx.lineTo(0, radius);
  ctx.quadraticCurveTo(0, 0, radius, 0);
  ctx.closePath();
  ctx.fill();

  ctx.fillStyle = textColor;
  ctx.font = `bold ${Math.floor(size * 0.42)}px sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(text.slice(0, 4), size / 2, size / 2);

  return canvas;
}

/**
 * Cria e baixa um pacote ZIP contendo os ícones de branding do app em várias resoluções
 * (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi, 512x512 play store, iOS, Web).
 */
export async function exportBrandingAssetsZip(config: AppConfig): Promise<void> {
  const zip = new JSZip();

  let sourceCanvas: HTMLCanvasElement | HTMLImageElement;

  if (config.uploadedIcon?.data) {
    const imageSrc = `data:image/png;base64,${config.uploadedIcon.data}`;
    try {
      sourceCanvas = await loadImage(imageSrc);
    } catch {
      sourceCanvas = renderFallbackIconCanvas(config, 512);
    }
  } else {
    sourceCanvas = renderFallbackIconCanvas(config, 512);
  }

  for (const variant of ICON_VARIANTS) {
    const canvas = document.createElement('canvas');
    canvas.width = variant.size;
    canvas.height = variant.size;
    const ctx = canvas.getContext('2d');
    if (ctx) {
      ctx.imageSmoothingEnabled = true;
      ctx.imageSmoothingQuality = 'high';
      ctx.drawImage(sourceCanvas, 0, 0, variant.size, variant.size);
      const base64Png = canvas.toDataURL('image/png').replace(/^data:image\/png;base64,/, '');
      zip.file(variant.path, base64Png, { base64: true });
    }
  }

  const readme = `BRANDING ASSETS FOR ${config.appName.toUpperCase()}
Package: ${config.packageName || 'com.example.app'}

Directory structure included:
- res/mipmap-mdpi/ic_launcher.png (48x48)
- res/mipmap-hdpi/ic_launcher.png (72x72)
- res/mipmap-xhdpi/ic_launcher.png (96x96)
- res/mipmap-xxhdpi/ic_launcher.png (144x144)
- res/mipmap-xxxhdpi/ic_launcher.png (192x192)
- store/play_store_512x512.png (512x512 High-Res Play Store Icon)
- ios/AppIcon.appiconset/Icon-1024.png (1024x1024 App Store Asset)
- web/ (Favicon and PWA icons)

Generated by Heavy Studio PRO v2.9
Date: ${new Date().toLocaleString()}
`;
  zip.file('README_BRANDING.txt', readme);

  const zipContent = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(zipContent);

  const cleanName = (config.appName || 'app')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_');

  const link = document.createElement('a');
  link.href = url;
  link.download = `${cleanName}_branding_assets.zip`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
